"""
Django settings for learning_django project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from django.contrib.messages import constants as messages

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = []
# 'localhost',
# '127.0.0.1',
# '111.222.333.444',
# 'mywebsite.example']

# Application definition

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

INSTALLED_APPS = [
    'daphne',
    'automated_resume.apps.AutomatedResumeConfig',
    'phonenumber_field',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'livereload',
    'django.contrib.staticfiles',
    'corsheaders',
    'channels',
    'django_celery_results',
    'celery_progress',
    'crispy_forms',
    'crispy_bootstrap5',
    'celery',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'livereload.middleware.LiveReloadScript',
]
# CORS_ALLOWED_ORIGINS =  [
#     'http://localhost:4200/',
# ]
# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Or your preferred backend
EMAIL_HOST = 'smtp.gmail.com'  # Or your email provider's SMTP server
EMAIL_PORT = 587  # Or the appropriate port for your provider (usually 587 or 465)
EMAIL_USE_TLS = True  # Or EMAIL_USE_SSL if your provider requires it
EMAIL_HOST_USER = os.getenv("KAUSTUBH_MAIL")  # Your email address
EMAIL_HOST_PASSWORD = os.getenv("APP_PASSWORD")  # Your app password (see below)

# Websocket Config
ASGI_APPLICATION = "learning_django.asgi.application"
# WebSockets Redis Backend
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",  # Use Redis in production
    },
}

# Cache setting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Celery Settings
CORS_ORIGIN_WHITELIST = ('http://localhost:4200',)
ROOT_URLCONF = 'learning_django.urls'
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis URL
CELERY_RESULT_BACKEND = 'django-db'  # For storing task results (optional)
CELERY_ACCEPT_CONTENT = ['json']  # Important for JSON serialization
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'  # Set your timezone
CELERY_TASK_ALWAYS_EAGER = False  # Set to True for local testing
CELERY_TASK_TRACK_STARTED = True  # Track when tasks start

# Optional: Configure retry settings
CELERY_TASK_RETRY_MAX_ATTEMPTS = 3  # Maximum retry attempts
CELERY_TASK_RETRY_BACKOFF = True  # Exponential backoff for retries
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# WSGI_APPLICATION = 'learning_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'automated_resume',
        'USER': 'root',
        'PASSWORD': os.getenv("MYSQL_PASSWORD"),
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

STATICFILES_DIRS = [
    BASE_DIR / "automated_resume/static/",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# Register Custom User Model
AUTH_USER_MODEL = 'automated_resume.CustomUser'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

LOGIN_REDIRECT_URL = "/home"
LOGOUT_REDIRECT_URL = ""
LOGIN_URL = "/login"

PATH_TO_JDS = "/Volumes/T7/PycharmProjects/Django/Resume_analyser/JDs"
VIDEO_UPLOAD_DIR = "recordings/"
RESUME_PATH = "resumes/"

# Coding Interface Questions Difficulty setup
FIRST_QUESTION_DIFFICULTY = "easy"
SECOND_QUESTION_DIFFICULTY = "medium"
