# Generated by Django 5.1.3 on 2025-03-11 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsetting',
            name='CODING_TIME_LIMIT',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='QUIZ_TIME_LIMIT',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
