# Generated by Django 5.1.3 on 2025-03-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0002_alter_adminsetting_coding_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='PASSING_PERCENT',
            field=models.FloatField(default=0.75),
        ),
    ]
