# Generated by Django 5.1.3 on 2025-03-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0003_adminsetting_passing_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
