# Generated by Django 5.1.3 on 2025-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0005_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('selected_model', models.CharField(max_length=100)),
                ('selected_fields', models.JSONField(default=list)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('line', 'Line Chart'), ('table', 'Table'), ('scatter', 'Scatter Plot'), ('histogram', 'Histogram'), ('boxplot', 'Box Plot'), ('heatmap', 'Heatmap'), ('bubble', 'Bubble Chart'), ('area', 'Area Chart'), ('violin', 'Violin Plot'), ('radar', 'Radar Chart'), ('donut', 'Donut Chart'), ('stacked_bar', 'Stacked Bar Chart'), ('funnel', 'Funnel Chart')], max_length=20)),
            ],
        ),
    ]
