# Generated by Django 5.1.3 on 2025-04-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0006_admindashboardconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=10)),
                ('problem_statement', models.TextField(max_length=500)),
                ('problem_description', models.TextField(max_length=500)),
                ('input_format', models.TextField(max_length=500)),
                ('output_format', models.TextField(max_length=500)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_test_case', models.TextField(max_length=500)),
                ('expected_output', models.TextField(max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('output_explanation', models.TextField(blank=True, max_length=500, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='automated_resume.questionbank')),
            ],
        ),
    ]
