# Generated by Django 5.1.3 on 2025-04-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0007_questionbank_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='problem_name',
            field=models.TextField(max_length=500),
        ),
    ]
