# Generated by Django 5.1.3 on 2025-04-24 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0008_alter_questionbank_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='input_format',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='output_format',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='problem_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='problem_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='problem_statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='expected_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='input_test_case',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='output_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CodingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('submitted_time', models.DateTimeField()),
                ('test_cases_passed', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_resume.questionbank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
