# Generated by Django 5.1.3 on 2025-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0009_alter_questionbank_input_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='FIRST_QUESTION_DIFFICULTY',
            field=models.CharField(default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='SECOND_QUESTION_DIFFICULTY',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
