# Generated by Django 5.1.3 on 2025-04-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0010_adminsetting_first_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='total_test_cases',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
