# Generated by Django 5.1.3 on 2025-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0011_codingresult_total_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='language_id',
            field=models.IntegerField(default=71),
            preserve_default=False,
        ),
    ]
