# Generated by Django 5.1.3 on 2025-04-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_resume', '0012_codingresult_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='flags_raised',
            field=models.IntegerField(default=0),
        ),
    ]
